baseURL = "https://www.analarapsicologa.com/"
languageCode = "es-ES"
paginate = 6
theme = "portio"
title = "Ana Lara"
# Main Menu
[[menu.main]]
name = "Inicio"
url = "#home"
weight = 1
[[menu.main]]
name = "Sobre mí"
url = "#about"
weight = 2
[[menu.main]]
name = "Servicios"
url = "#service"
weight = 3
[[menu.main]]
name = "Testimonios"
url = "#testimonial"
weight = 4

# # Sitemap Menu
# [[menu.sitemap]]
# name = "About me"
# url = "about"
# weight = 1
# [[menu.sitemap]]
# name = "Frequently Ask Question"
# url = "#"
# weight = 2
# [[menu.sitemap]]
# name = "Privacy & Policy"
# url = "#"
# weight = 3
# [[menu.sitemap]]
# name = "Latest Article"
# url = "#"
# weight = 4

[params]
blogPageURL = "about"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/logo/logo_white.svg"

# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/gCYfe9N"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/logo/logo_black.svg"

[params.address]
address = "Lucero Psicología (Edificio Viapol, Sevilla)"
email = "analarapsicologa@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "(+34) 643 895 768"

[params.map]
url = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3170.449359856744!2d-5.980842487819946!3d37.379204071971195!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd126e98cb0eda5f%3A0x7302337f4e6b3a85!2sEdificio%20Viapol!5e0!3m2!1sen!2ses!4v1695400142589!5m2!1sen!2ses"

# # Social icons
# [[params.social]]
# icon = "fa-facebook-official"
# url = "https://www.facebook.com/"
# weight = 1
# [[params.social]]
# icon = "fa-linkedin-square"
# url = "https://www.linkedin.com/"
# weight = 2
# [[params.social]]
# icon = "fa-pinterest-square"
# url = "https://www.pinterest.com/"
# weight = 3
# [[params.social]]
# icon = "fa-twitter-square"
# url = "https://twitter.com/"
# weight = 4
# 

# disable all services
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true